data:
  train_transforms:
    image_size: [320, 64]
    augs: 0
    transform_dict:
      OpticalDistortion:
        distort_limit: 1
        shift_limit: 0.5
        p: 0.1
      GridDistortion:
        num_steps: 5
        distort_limit: 0.3
        interpolation: 1
        border_mode: 4
        p: 0.1
      ColorJitter:
        brightness: [ 0.6, 0.8 ]
        contrast: [ 0.6, 0.8 ]
        saturation: 0.
        hue: 0.
        p: 0.5
#      RandomFog:
#        fog_coef_lower: 0.1
#        fog_coef_upper: 0.1
#        alpha_coef: 0.05
#        p: 0.1
  val_transforms:
    image_size: [320, 64]
  batch_size: 64
  path: '../contest02/data'
  num_workers: 8
Adam_stage:
  epoch: 5
  save_mod: 5
  log_window_size: 10
  opt_class: Adam
  scheduler_class: StepLR
  scheduler_params:
    step_size: 1
    gamma: 0.1
model:
  name: baseline
  params:
    cnn_input_size: [64, 320]
    cnn_output_len: 20
    rnn_hidden_size: 128
    rnn_num_layers: 1
    rnn_dropout: 0.0
    rnn_bidirectional: False
