data:
  train_transforms:
    image_size: [320, 64]
    augs: 0
    transform_dict:
      ColorJitter:
        brightness: [0.7, 1.1]
        contrast: [0.7, 1.1]
        saturation: 0.2
        hue: 0.
        p: 0.5
  val_transforms:
    image_size: [320, 64]
  batch_size: 64
  path: '../contest02/data'
  num_workers: 8
Adam_stage:
  epoch: 5
  save_mod: 5
  log_window_size: 10
  opt_class: Adam
  scheduler_class: StepLR
  scheduler_params:
    step_size: 1
    gamma: 0.1
model:
  name: baseline
  params:
    cnn_input_size: [64, 320]
    cnn_output_len: 20
    rnn_hidden_size: 128
    rnn_num_layers: 1
    rnn_dropout: 0.0
    rnn_bidirectional: False
