data:
  reweight_deg: 4
  train_transforms:
    image_size: 512
    transform_dict:
      GridDistortion:
        num_steps: 5
        distort_limit: 0.3
        interpolation: 1
        border_mode: 4
        p: 0.1
#      RGBShift:
#        r_shift_limit: 5
#        g_shift_limit: 5
#        b_shift_limit: 5
#        p: 0.1
      ColorJitter:
        brightness: [ 0.5, 1. ]
        contrast: [ 0.5, 1. ]
        saturation: 0.
        hue: 0.
        p: 0.5
      RandomFog:
        fog_coef_lower: 0.1
        fog_coef_upper: 0.5
        alpha_coef: 0.08
        p: 0.1
  val_transforms:
    image_size: 512
  batch_size: 8
  path: '../contest02/data'
  num_workers: 8
Adam_stage:
  weight_focal: 0.8
  focal_gamma: 4
  epoch: 2
  save_mod: 5
  log_window_size: 10
  opt_class: Adam
  scheduler_class: StepLR
  scheduler_params:
    step_size: 1
    gamma: 0.1
model:
  freeze_bn: True
  name: baseline
  params:
    encoder_name: resnet34
    encoder_weights: imagenet
    in_channels: 3
    classes: 1
    decoder_attention_type: scse
