data:
  train_transforms:
    image_size: 128
  val_transforms:
    image_size: 128
  batch_size: 32
  path: '../contest02/data'
  num_workers: 8
Adam_stage:
  weight_bce: 1.
  epoch: 1
  save_mod: 5
  log_window_size: 10
  opt_class: Adam
model:
  name: baseline
  params:
    encoder_name: resnet34
    encoder_weights: imagenet
    in_channels: 3
    classes: 1
