data_path: '../contest02/data'
rec_size: [320, 64]
seg_size: [512, 512]
seg_threshold: 0.1
min_wh_odd: 1.
max_wh_odd: 10
output_file: 512_aug.csv
seg_model:
  name: baseline
  path: model_save/segmentation_17m49fm1/Adam_stage-seg_model_best.pt
  params:
    encoder_name: resnet34
    encoder_weights: imagenet
    in_channels: 3
    classes: 1
    decoder_attention_type: scse
rec_model:
  name: baseline
  path: model_save/recognition_3oio66i0/Adam_stage-rec_model_best.pt
  params:
    cnn_input_size: [64, 320]
    cnn_output_len: 20
    rnn_hidden_size: 256
    rnn_num_layers: 1
    rnn_dropout: 0.2
    rnn_bidirectional: True