data_path: '../contest02/data'
rec_size: [320, 64]
seg_size: [512, 512]
seg_threshold: 0.1
min_wh_odd: 1.
max_wh_odd: 10
output_file: 512_seg.csv
seg_model:
  name: baseline
  path: model_save/segmentation_2gicqc42/Adam_stage-seg_model_best.pt
  params:
    encoder_name: resnet34
    encoder_weights: imagenet
    in_channels: 3
    classes: 1
rec_model:
  name: baseline
  path: model_save/recognition_2eol4n5p/Adam_stage-rec_model_best.pt
  params:
    cnn_input_size: [64, 320]
    cnn_output_len: 20
    rnn_hidden_size: 128
    rnn_num_layers: 1
    rnn_dropout: 0.0
    rnn_bidirectional: False